### ISSUE TITLE
Please use Unix-style slashes when generating GlobalUsings.cs in Mac/Linux

### ISSUE THREAD

**Issue by Emik03** [bjorndaniel/GlobalUsingsAnalyzer#6]
When applying the lint in a solution in which projects aren't within the same directory, the file incorrectly gets placed on `Solution/Project\GlobalUsings.cs` as oppose to `Solution/Project/GlobalUsings.cs`. Please use [`Path.DirectorySeparatorChar`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=net-7.0) as oppose to `\` when concatenating paths so that it works platform-independently.

![image](https://user-images.githubusercontent.com/14614115/214061439-dbc76981-2a1f-4448-8707-4a961a1af926.png)
![image](https://user-images.githubusercontent.com/14614115/214062646-e3df94e3-4165-48d4-b2d4-c236ce9a60d0.png)

**Comment by bjorndaniel** [comment]
Thanks for the detailed description (and the correct solution :))!
I completely forgot to test this on something other than Windows.
This should now be fixed in verson 1.2
